### ISSUE TITLE
passwords recognizable in plain text

### ISSUE THREAD

**Issue by devnull069** [nextcloud/integration_zimbra#23]
Hi,

through the zimbra integration you can find out clear text passwords on the nextcloud server using the console!

`sudo -u www-data php /var/www/nextcloud/occ user:setting USERNAME`

```
  - integration_zimbra:
    - url: https://zimbra.your-domain.net/
    - login: ********
    - password: **CLEARTEXTPASSWORD**
    - user_name: **********************
    - user_id: xxxx.xxxx.xxxx.xxxx
    - user_displayname: ********
```
